name: Retrieve Contentful CDA Token and Space ID

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve Secrets
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Retrieve Contentful Secrets
        run: |
          echo "CDA_TOKEN=$CDA_TOKEN" >> $GITHUB_ENV
        env:
          CDA_TOKEN: ${{ secrets.CDA_ACCESS_TOKEN }}

      # Additional steps in your workflow that require CDA token and Space ID
