name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create configuration file
        run: |
          echo "const secrets = {" > config.js
          echo "  apiKey: '${{ secrets.CDA_ACCESS_TOKEN }}'," >> config.js
          # Add more secrets as needed
          echo "};" >> config.js
          echo "export default secrets;" >> config.js
